server.port=8218

spring.data.mongodb.uri=mongodb+srv://paulita1804_db_user:Jungkook18@empresariales1.y5v2h0j.mongodb.net/futbolclub

spring.jackson.serialization.write-dates-as-timestamps=false
spring.thymeleaf.cache=false
